name: WorldEconomy
version: alpha 0.0.5_03
main: io.github.SebastianDanielFrenz.WorldEconomyPlugin.WorldEconomyPlugin
commands:
  we:
    help: type "/we help" for help.
api-version: 1.13
load: startup